### ISSUE TITLE
Server update to 1.10.3

### ISSUE THREAD

**Issue by GeneralZyonix** [The-Nexus-Project/Limitless-3#186]
When starting my server is says the following

> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
> 	Phosphophyllite (phosphophyllite) has failed to load correctly
> §7java.lang.IllegalStateException: Performant is incompatible with Phosphophyllite
> This is a known issue with performant and it breaking other mods, the author does not care
> GitHub issue on the matter: https://github.com/someaddons/performant_issues/issues/70
> To bypass this check add "bypassPerformantCheck: true" to your phosphophyllite config
> If you bypass this check I (RogueLogix) will not provide any support for any issues related to Phosphophyllite or the mods that use it
> If you believe your issue is unrelated, disable performant and reproduce it
> By choosing to bypass this check you understand that here there be dragons

Which one should i remove?

**Comment by Gbergz** [comment]
Try a re-install of the server. This shouldnt be happening.

**Comment by GeneralZyonix** [comment]
Reinstalling as we speak

**Comment by GeneralZyonix** [comment]
So i just did the Update again on my server and still the same error

> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Phosphophyllite (phosphophyllite) has failed to load correctly
§7java.lang.IllegalStateException: Performant is incompatible with Phosphophyllite
This is a known issue with performant and it breaking other mods, the author does not care
GitHub issue on the matter: https://github.com/someaddons/performant_issues/issues/70
To bypass this check add "bypassPerformantCheck: true" to your phosphophyllite config
If you bypass this check I (RogueLogix) will not provide any support for any issues related to Phosphophyllite or the mods that use it
If you believe your issue is unrelated, disable performant and reproduce it
By choosing to bypass this check you understand that here there be dragons
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.18.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.18.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.18.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.18.jar:?]

Should i try making a new server and dragging my world to it?

**Comment by GeneralZyonix** [comment]
Full server reinstall worked
