### ISSUE TITLE
smoothfocus and transliterationlib failed to load

### ISSUE THREAD

**Issue by toetoe22** [The-Nexus-Project/Limitless-3#192]
### Describe your issue, what happened?
Unable to load server due to following errors. 

### To Reproduce
first time opening the server files to initiate server and i get the error

### Crash Reports & Logs (Don't paste entire crash reports here.)

Crash Report UUID: 50ba067b-6348-416b-8aa8-97805d278c43
    Suspected Mods: Forge (forge), Forge (forge)[00:32:52 [main/FATAL] [minecraft/Main]: Failed to start the minecraft server]
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
    SmoothFocus (smoothfocus) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER,
    TRansliterationLib Mod (transliterationlib) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
]
    at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] -re:classloading-
    at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] -re:classloading-
    at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] -re:classloading-
    at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] -re:classloading-
    at net.minecraft.server.Main.main(Main.java:95) ~[?:?] -re:classloading,re:mixin,pl:mixin:A-
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] --
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] --
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] --
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] --
    at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.25.jar:36.1] --
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] -re:classloading-
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] -re:classloading-
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] -re:classloading-
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] -re:classloading-
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] -re:classloading-
    at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.25.jar:?] -re:classloading-
    at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.25.jar:?] -re:classloading-
    at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.25.jar:?] -re:classloading-
Console >

**Comment by Gbergz** [comment]
transliterationlib is not even in Limitless 3, it was recently added to Limitless Lite though, maybe you meant to report it there?

**Comment by toetoe22** [comment]
oops my bad, youre right

**Comment by Gbergz** [comment]
No need to re-open there, I re-released the server files for the Limitless Lite update. Redownload it and it should work.
Forgot to remove transliterationlib in the server files.
