### ISSUE TITLE
Tried to install latest version with server setup and got error

### ISSUE THREAD

**Issue by Bell-riya** [The-Nexus-Project/Limitless-3#248]
Tried to install server zip compilation and get this error after all mods installed, after I tried to install a forge that needed - it's keep saying that it's missing libraries

**Comment by Bell-riya** [comment]
[19:10:40] [INFO] [ 372/372] Downloaded mod: atmospheric-1.16.5-3.1.1.jar
[19:10:40] [INFO] Attempting to download installer from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.22/forge-1.16.5-36.2.22-installer.jar
[19:10:41] [ERROR] Problem while installing Loader from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.22/forge-1.16.5-36.2.22-installer.jar

java.io.IOException: Expected a SETTINGS frame but was GOAWAY
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:115)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[19:10:41] [ERROR] Stopping the process as downloading the ModLoader failed

atm.bloodworkxgaming.serverstarter.DownloadLoaderException: Problem while installing Loader from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.22/forge-1.16.5-36.2.22-installer.jar
        at atm.bloodworkxgaming.serverstarter.LoaderManager.installLoader(LoaderManager.kt:168)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:169)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:204)
Caused by: java.io.IOException: Expected a SETTINGS frame but was GOAWAY
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:115)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Для продолжения нажмите любую клавишу . . .

**Comment by Gbergz** [comment]
Looks to be a network issue, just tried the installer on my side and things are working smoothly. Don't know much more about this specific issue.

Try rebooting PC, Internet etc.

**Comment by Bell-riya** [comment]
Also don't work on the previsious versions like 1.10.3, I'll try smth and then reboot PC and Internet

**Comment by Bell-riya** [comment]
My friend tried to install like me and he got no problems, looks like it's problem with me.
