### ISSUE TITLE
version 1.8.3  Update seems to cause crash loop with Silent's Mechanisms

### ISSUE THREAD

**Issue by ryanj1792** [The-Nexus-Project/Limitless-3#74]
version 1.8.3

Update seems to cause crash loop 

server completely down after crash had to reload a back up 

java.lang.NoSuchMethodError: net.minecraft.tags.TagRegistryManager.func_242191_a()V
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.isFuel(CoalGeneratorTileEntity.java:36) ~[silents_mechanisms:0.8.8+73] {re:classloading}
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.hasFuel(CoalGeneratorTileEntity.java:47) ~[silents_mechanisms:0.8.8+73] {re:classloading}
	at net.silentchaos512.mechanisms.block.generator.AbstractGeneratorTileEntity.func_73660_a(AbstractGeneratorTileEntity.java:91) ~[silents_mechanisms:0.8.8+73] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:1279) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.isFuel(CoalGeneratorTileEntity.java:36) ~[silents_mechanisms:0.8.8+73] {re:classloading}
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.hasFuel(CoalGeneratorTileEntity.java:47) ~[silents_mechanisms:0.8.8+73] {re:classloading}
	at net.silentchaos512.mechanisms.block.generator.AbstractGeneratorTileEntity.func_73660_a(AbstractGeneratorTileEntity.java:91) ~[silents_mechanisms:0.8.8+73] {re:classloading}
-- Block entity being ticked --
Details:
	Name: silents_mechanisms:coal_generator // net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity
	Block: Block{silents_mechanisms:coal_generator}[facing=west,lit=false]
	Block location: World: (-1075,67,-249), Chunk: (at 13,4,7 in -68,-16; contains blocks -1088,0,-256 to -1073,255,-241), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Block: Block{silents_mechanisms:coal_generator}[facing=west,lit=false]
	Block location: World: (-1075,67,-249), Chunk: (at 13,4,7 in -68,-16; contains blocks -1088,0,-256 to -1073,255,-241), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:1279) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Gbergz** [comment]
Read.
(Don't paste entire crash reports here.)

**Comment by choekstr** [comment]
Since this is the only issue so far, i'll tack on to this one instead of create yet a new one.  After updating to 1.8.3, and similarly 1.8.3a my SSP world crashes now and I haven't been able to figure out why all afternoon/evening.  
In my crash file there was a reference to performant so I removed that: nope.  Then IE, so I removed it (haven't done much with IE other than a water wheel as a loot bag reward).  
I tried reverting to an older save.  
I tried using multimc instead of curseforge/overwolf, I tried removing options.txt and other personal config, all to no avail.

For whatever reason, my world doesn't like the new updates so I reverted back to 1.8.2 and just copied over the kubejs cloche folder since that is a really nice update.

I'm not expecting any solution, just mentioning it here in case others were having issues as the OP seems to have a similar issue.

**Comment by SkuxxDeluxe** [comment]
-1075,67,-249
 The block at this location, probably a coal generator seems to be the problem. Can try MCedit -ing it out.

**Comment by poison96** [comment]
I have had similar issue however with new server running on v1.8.3a. Placing a coal generator from Silent's mechanisms crashes the server as per crash log and crashes on each startup.

https://pastebin.com/qJKGsken

**Comment by Xplodin** [comment]
Also crashes in SP.
I cant even place a coal gen without the game shitting itself

https://pastebin.com/QwiqqMUA 

somehow its saying alexs mobs with orca is causing it idk how

**Comment by choekstr** [comment]
ahh, I have a silent's mechanisms coal generator as well and might be what's crashing the world when I load in with the new version.  One should be able to just back-rev silent's and keep the rest of the mods at the latest versions and it should work.  One could also just get rid of the generator in the 1.8.2 world, then upgrade to 1.8.3a.  

Just documenting ideas for others to try...

**EDIT:  This was indeed the fix.  I broke the Silent's coal generator and then the world loaded up just fine.**

**Comment by Azreil** [comment]
> ahh, I have a silent's mechanisms coal generator as well and might be what's crashing the world when I load in with the new version. One should be able to just back-rev silent's and keep the rest of the mods at the latest versions and it should work. One could also just get rid of the generator in the 1.8.2 world, then upgrade to 1.8.3a.
> 
> Just documenting ideas for others to try...
> 
> **EDIT: This was indeed the fix. I broke the Silent's coal generator and then the world loaded up just fine.**

I used an earlier version of Silent Mechanisms, but the coal gen still crashed my SSP. There is only the one in the pack with 1.8.3a (SilentMechanisms-1.16.3-0.8.8+73.jar), and then the original version (SilentMechanisms-1.16.3-0.8.7+72.jar). These are the only two versions listed in the curse forge app and both cause the crash when placing the coal gen.

I have only played for maybe an hour, 2 max. I stuck close to spawn in my world and havent really done much. Minecraft vanilla quests up to Iron and have made an AE grindstone. So anything causing this crash has to do specifically with Silent Mech coal gen and something to do with the backround world interactions in the 1.8.3a patch. Not sure really, I didnt spend much time in world and didnt thoroughly research all the mods and data packs. I will look more into it and will post if I find more.

**EDIT** I have checked multiple crash logs and found that it only has Coal gen for common factors. There doesnt seem to be anything else involved. 2 of 7 report GorrilaForage.Leaves, but the others dont include any "alexsmobs". I also checked if "Silent Mech" was update from 1.8.2 and it is same version in 1.8.3 and 1.8.3a. I will begin testing other older versions later, but I am going to focus on testing only the things that was changed in the new Pack version. I will start with Forge versions and the new mods added. Will further update when I find something more.

**EDIT 2** I have now confirmed that it is in fact "Alexsmobs" causing the issue. Not sure how, but With a fresh install of 1.8.3a, then using my Uncorrupted world data just prior to putting down the coal gen. I disabled one by one all the new mods first, then disabled the updated mods. After having only alexsmobs disabled I was able to place down the coal gen, waited 20 minutes with no crash.
I can see Alexsmobs 1.1.1 is on the 1.8.2 when things were working. With 1.8.3 and later the version used is 1.3. I did some testing and "alexsmobs-1.2.1.jar" is the latest version that is stable with the Coal Gen. So If we update to that one it will work again.
**For now**, Anyone on SSP, should either disable or install version "alexsmobs-1.2.1.jar" of Alexsmobs so they can use Silent Mechanisms Coal Gen.
Side note: The coal gen doesnt burn fuel. (coal, logs, planks tried)

**Comment by choekstr** [comment]
@Azreil you can try various versions on curseforge.com as there are 8 versions listed on there if you care to try a few older versions.  

I was using the silent's mechanisms coal generator when I started the pack in mid Nov until just yesterday until something got updated in the 1.8.3 and 1.8.3a version.  Perhaps no version of older silent's mechanisms will work now but worth trying if you watned to salvage your world.  Like you said, not much progress so might be just as easy to start a new world.

**Comment by Irgendwer01** [comment]
@Azreil My server got the same issue, i disabled Alex's Mobs but the Server still crashed with same crash log
the crash log: https://paste.ubuntu.com/p/jwtvDZDb7T/

**Comment by choekstr** [comment]
Perhaps until this is fixed you could add the following to the server_scripts\removed.js so people don't inadvertently crash their world:
`	  event.remove({id: 'silents_mechanisms:coal_generator'})
`
This leaves the item in JEI but won't let them see a recipe for it.  A nice way to show it isn't craftable at the moment.
Just an idea based on what I did on my server to protect the users...

**Comment by Gbergz** [comment]
@choekstr This is what we already have on the Official Server aswell. Thank you though. I will consider it.

**Comment by choekstr** [comment]
and maybe for the iron furnace(s) too since those are crashing as well, right?  More thinking out loud here for my own server, but might help others as well.

**Comment by Gbergz** [comment]
v1.9.0 probably fixes this. Give it a go.
Re-open if it still happening on 1.9.0
